[build]
  command = "npm ci && npm run build"
  publish = "dist"

[build.environment]
  VITE_API_URL = "https://botback-q7v3.onrender.com"
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200